// <auto-generated />
namespace Joes_Pub_MVC_4.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Cachechange : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Cachechange));
        
        string IMigrationMetadata.Id
        {
            get { return "201301180947417_Cachechange"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
